trigger:
- main

pool:
  vmImage: 'ubuntu-latest' 

variables:
  imageName: 'kahlai/pipelines-javascript-docker'
  GLOBAL_PAT: $(PAT)
  GLOBAL_PAT2: $(PAT2)

steps:
- task: Docker@2
  displayName: Build an image and push
  inputs:
    containerRegistry: 'Quay'
    repository: $(imageName)
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
# - checkout: self
#   persistCredentials: true
- bash: |
    echo 'Hello World'
    echo "Using an input-macro works: $(PAT2)"
    echo "Using an input-macro works: $GLOBAL_PAT2"
    git config --global user.name "kahlai"
    git config credential.username "kahlai"
    git config --global user.email "kahlai@redhat.com"
    git clone https://kahlai:$(PAT2)@github.com/kahlai/azure-pipeline-demo.git
    cd azure-pipeline-demo
    touch README.md
    echo "some text here" > README.md
    git add README.md
    echo $(PAT2)
    git commit -m "first commit"
    git push origin
  env: # Variables to map into the process's environment.
    PAT: $(PAT) # Name/value pairs
# - task: GitHubRelease@1
#   inputs:
#     gitHubConnection: 'Github'
#     repositoryName: '$(Build.Repository.Name)'
#     action: 'create'
#     target: '$(Build.SourceVersion)'
#     tagSource: 'gitTag'
#     changeLogCompareToRelease: 'lastFullRelease'
#     changeLogType: 'commitBased'
    