trigger:
- main

pool:
  vmImage: 'ubuntu-latest' 

variables:
  imageName: 'kahlai/pipelines-javascript-docker'

steps:
- task: Docker@2
  displayName: Build an image and push
  inputs:
    containerRegistry: 'Quay'
    repository: $(imageName)
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
- script: echo 'Hello World'
- task: GitHubRelease@1
  inputs:
    gitHubConnection: 'Github'
    repositoryName: '$(Build.Repository.Name)'
    action: 'create'
    target: '$(Build.SourceVersion)'
    tagSource: 'gitTag'
    changeLogCompareToRelease: 'lastFullRelease'
    changeLogType: 'commitBased'
    