trigger:
- main

pool:
  vmImage: 'ubuntu-latest' 

variables:
  imageName: 'kahlai/pipelines-javascript-docker'

steps:
- task: Docker@2
  displayName: Build an image and push
  inputs:
    containerRegistry: 'Quay'
    repository: $(imageName)
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
- script: |
    echo 'Hello World'
    git config --global user.name "Mona Lisa"
    git config --global user.email "monalisa@redhat.com"
    git clone https://github.com/kahlai/azure-pipeline-demo.git
    touch README.md
    git add README.md
    git commit -m "first commit"
    git push
- task: GitHubRelease@1
  inputs:
    gitHubConnection: 'Github'
    repositoryName: '$(Build.Repository.Name)'
    action: 'create'
    target: '$(Build.SourceVersion)'
    tagSource: 'gitTag'
    changeLogCompareToRelease: 'lastFullRelease'
    changeLogType: 'commitBased'
    